source 'https://rubygems.org'
ruby "2.3.0"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'unicorn'
gem 'cucumber'
gem 'minitest'
gem 'rest_client'
gem 'json'
gem 'bunny'
gem 'aws-sdk'